version: 2.1
description: An inline orb for common groups of Gradle commands

orbs:
  connexta-gradle:
    executors:
      base-executor:
        docker:
          - image: circleci/openjdk:11-jdk
    commands:
      build:
        steps:
          - checkout
          - run: ./gradlew clean build -x test
      test:
        steps:
          - checkout
          - run: ./gradlew clean build
      scan:
        steps:
          - checkout
          - run: ./gradlew dependencyCheckAnalyze
    jobs:
      full-build:
        executor: base-executor
        steps:
          - build
          - test
          - scan

workflows:
  main:
    jobs:
      - connexta-gradle/full-build