# Compile Code, Unit Test, Scan Dependencies, Build Image, Scan Image

version: 2.1
orbs:
  anchore: anchore/anchore-engine@1.4.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: ./gradlew clean build -x test
  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: ./gradlew clean build
  dependency-scan:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: ./gradlew dependencyCheckAnalyze
  image-scan:
    executor: anchore/anchore_engine
    steps:
      - setup_remote_docker
      - checkout
      - run:
          command: 'docker build -t "localhost:5000/circle-test:latest" .'
      - anchore/analyze_local_image:
          dockerfile_path: ./Dockerfile
          image_name: 'localhost:5000/circle-test:latest'
          policy_bundle_file_path: .circleci/.anchore/policy_bundle.json
          policy_failure: true
          timeout: '500'
      - anchore/parse_reports
      - store_artifacts:
          path: anchore-reports
  deploy:
    steps:
      - setup_remote_docker
      - checkout
      - run:
          command: 'docker build -t "localhost:5000/circle-test:latest" .'
          command: 'docker push localhost:5000/circle-test:latest'

workflows:
  fullrun:
    jobs:
      - build
      - test:
          requires:
            - build
      - dependency-scan:
          requires:
            - test
      - image-scan:
          requires:
            - test
      - deploy:
          requires:
            - dependency-scan
            - image-scan